In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import LabelEncoder

In [18]:
data = pd.read_csv("GaltonFamilies.csv")
data['Height'] = data['childHeight']
data = data.drop(columns = ['childHeight','rownames','family','midparentHeight'])

label_encoder = LabelEncoder()
data['gender'] = label_encoder.fit_transform(data['gender'])
data['father'] = data['father']*2.54
data['mother'] = data['mother']*2.54
data['Height'] = data['Height']*2.54
data

     father  mother  children  childNum  gender   Height
0    199.39  170.18         4         1       1  185.928
1    199.39  170.18         4         2       0  175.768
2    199.39  170.18         4         3       0  175.260
3    199.39  170.18         4         4       0  175.260
4    191.77  168.91         4         1       1  186.690
..      ...     ...       ...       ...     ...      ...
929  157.48  167.64         3         1       1  162.560
930  157.48  167.64         3         2       0  157.480
931  157.48  167.64         3         3       0  154.940
932  158.75  160.02         2         1       1  168.910
933  158.75  160.02         2         2       0  144.780

[934 rows x 6 columns]

In [28]:

X = data[['father', 'mother', 'children', 'childNum','gender']] 

y = data['Height']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=30)

model = RandomForestRegressor(random_state=30)


model.fit(X_train, y_train)


y_pred = model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
r2 = r2_score(y_test, y_pred)
print(f"R2 score is :{r2}")


example_input = [[170, 165, 5, 5,1]] 
predicted_height = model.predict(example_input)
print(f"Predicted Height: {predicted_height[0]:.2f} meters")

Mean Squared Error: 18.89682579017044
R2 score is :0.8039214070326
Predicted Height: 171.59 meters

C:\Users\SHIV\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [29]:
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)